import type { Metadata } from 'next'
import { Inter, Almarai, Cairo } from 'next/font/google'
import '../globals.css'
import { getLangDir } from 'rtl-detect'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { unstable_setRequestLocale } from 'next-intl/server'

const inter = Inter({ subsets: ['latin'] })
const almarai = Almarai({
  subsets: ['arabic'],
  weight: ['300', '400', '700', '800'],
})

const cairo = Cairo({
  subsets: ['arabic'],
  weight: ['300', '400', '700', '800'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
  params: { locale: string }
}

export default async function RootLayout({
  children,
  params: { locale },
}: Props) {
  unstable_setRequestLocale(locale)
  const direction = getLangDir(locale)
  const messages = await getMessages()
  const mainFont = locale === 'ar' ? almarai : inter
  return (
    <html lang={locale} dir={direction}>
      <body className={mainFont.className}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
